# Generated by Django 3.1.2 on 2020-10-29 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('corparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('groupRights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.grouprights')),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee'),
        ),
    ]
