# Generated by Django 3.1.2 on 2020-10-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20201029_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.employee'),
        ),
    ]
