# Generated by Django 3.1.2 on 2020-10-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20201029_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='corparation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='groupRights',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.grouprights'),
        ),
    ]
