# Generated by Django 3.1.2 on 2020-10-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20201029_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='corparation',
        ),
        migrations.AlterField(
            model_name='employee',
            name='groupRights',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.grouprights'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='director',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='organization.employee'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('workman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee')),
            ],
        ),
    ]
